// Code generated by protoc-gen-go.
// source: projects.proto
// DO NOT EDIT!

/*
Package projects is a generated protocol buffer package.

It is generated from these files:
	projects.proto

It has these top-level messages:
	CreateRequest
	RetrieveRequest
	ProjectResponse
	AddMemberRequest
	RemoveMemberRequest
	InviteRequest
	InviteStatusResponse
	ActionInviteRequest
	MemberStatusResponse
	GetMembersRequest
	GetProjectsRequest
	MembersResponse
	ProjectsResponse
*/
package projects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_SANDBOX    Mode = 0
	Mode_PRODUCTION Mode = 1
)

var Mode_name = map[int32]string{
	0: "SANDBOX",
	1: "PRODUCTION",
}
var Mode_value = map[string]int32{
	"SANDBOX":    0,
	"PRODUCTION": 1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Region int32

const (
	Region_GLOBAL Region = 0
	Region_US     Region = 1
	Region_EUROPE Region = 2
	Region_ASIA   Region = 3
)

var Region_name = map[int32]string{
	0: "GLOBAL",
	1: "US",
	2: "EUROPE",
	3: "ASIA",
}
var Region_value = map[string]int32{
	"GLOBAL": 0,
	"US":     1,
	"EUROPE": 2,
	"ASIA":   3,
}

func (x Region) String() string {
	return proto.EnumName(Region_name, int32(x))
}
func (Region) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MemberType int32

const (
	MemberType_OWNER   MemberType = 0
	MemberType_MEMBER  MemberType = 1
	MemberType_VIEWER  MemberType = 2
	MemberType_SUPPORT MemberType = 3
)

var MemberType_name = map[int32]string{
	0: "OWNER",
	1: "MEMBER",
	2: "VIEWER",
	3: "SUPPORT",
}
var MemberType_value = map[string]int32{
	"OWNER":   0,
	"MEMBER":  1,
	"VIEWER":  2,
	"SUPPORT": 3,
}

func (x MemberType) String() string {
	return proto.EnumName(MemberType_name, int32(x))
}
func (MemberType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InviteStatus int32

const (
	InviteStatus_PENDING   InviteStatus = 0
	InviteStatus_ACCEPTED  InviteStatus = 1
	InviteStatus_REJECTED  InviteStatus = 2
	InviteStatus_EXPIRED   InviteStatus = 3
	InviteStatus_NOT_FOUND InviteStatus = 4
)

var InviteStatus_name = map[int32]string{
	0: "PENDING",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "EXPIRED",
	4: "NOT_FOUND",
}
var InviteStatus_value = map[string]int32{
	"PENDING":   0,
	"ACCEPTED":  1,
	"REJECTED":  2,
	"EXPIRED":   3,
	"NOT_FOUND": 4,
}

func (x InviteStatus) String() string {
	return proto.EnumName(InviteStatus_name, int32(x))
}
func (InviteStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateRequest struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DistributorId string `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Mode          Mode   `protobuf:"varint,4,opt,name=mode,enum=projects.Mode" json:"mode,omitempty"`
	Region        Region `protobuf:"varint,5,opt,name=region,enum=projects.Region" json:"region,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *CreateRequest) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *CreateRequest) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

type RetrieveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RetrieveRequest) Reset()                    { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()               {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RetrieveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectResponse struct {
	Id            string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DistributorId string                     `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Mode          Mode                       `protobuf:"varint,4,opt,name=mode,enum=projects.Mode" json:"mode,omitempty"`
	Region        Region                     `protobuf:"varint,5,opt,name=region,enum=projects.Region" json:"region,omitempty"`
	Created       *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
}

func (m *ProjectResponse) Reset()                    { *m = ProjectResponse{} }
func (m *ProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectResponse) ProtoMessage()               {}
func (*ProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectResponse) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *ProjectResponse) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *ProjectResponse) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

func (m *ProjectResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type AddMemberRequest struct {
	MemberId  string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Type      MemberType                 `protobuf:"varint,3,opt,name=type,enum=projects.MemberType" json:"type,omitempty"`
	Expiry    *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *AddMemberRequest) Reset()                    { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()               {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *AddMemberRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AddMemberRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *AddMemberRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type RemoveMemberRequest struct {
	MemberId  string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *RemoveMemberRequest) Reset()                    { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()               {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *RemoveMemberRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type InviteRequest struct {
	Email     string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	ProjectId string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Type      MemberType                 `protobuf:"varint,3,opt,name=type,enum=projects.MemberType" json:"type,omitempty"`
	Expiry    *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *InviteRequest) Reset()                    { *m = InviteRequest{} }
func (m *InviteRequest) String() string            { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()               {}
func (*InviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *InviteRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *InviteRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type InviteStatusResponse struct {
	Email        string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Status       InviteStatus               `protobuf:"varint,2,opt,name=status,enum=projects.InviteStatus" json:"status,omitempty"`
	Verification string                     `protobuf:"bytes,3,opt,name=verification" json:"verification,omitempty"`
	Created      *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Actioned     *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=actioned" json:"actioned,omitempty"`
}

func (m *InviteStatusResponse) Reset()                    { *m = InviteStatusResponse{} }
func (m *InviteStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*InviteStatusResponse) ProtoMessage()               {}
func (*InviteStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InviteStatusResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteStatusResponse) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *InviteStatusResponse) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

func (m *InviteStatusResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *InviteStatusResponse) GetActioned() *google_protobuf.Timestamp {
	if m != nil {
		return m.Actioned
	}
	return nil
}

type ActionInviteRequest struct {
	Email        string       `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	ProjectId    string       `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	MemberId     string       `protobuf:"bytes,3,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	Status       InviteStatus `protobuf:"varint,4,opt,name=status,enum=projects.InviteStatus" json:"status,omitempty"`
	Verification string       `protobuf:"bytes,5,opt,name=verification" json:"verification,omitempty"`
}

func (m *ActionInviteRequest) Reset()                    { *m = ActionInviteRequest{} }
func (m *ActionInviteRequest) String() string            { return proto.CompactTextString(m) }
func (*ActionInviteRequest) ProtoMessage()               {}
func (*ActionInviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ActionInviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ActionInviteRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ActionInviteRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *ActionInviteRequest) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *ActionInviteRequest) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

type MemberStatusResponse struct {
	MemberId  string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Type      MemberType                 `protobuf:"varint,3,opt,name=type,enum=projects.MemberType" json:"type,omitempty"`
	Invited   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=invited" json:"invited,omitempty"`
	Expiry    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=expiry" json:"expiry,omitempty"`
	Joined    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=joined" json:"joined,omitempty"`
	Detached  *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=detached" json:"detached,omitempty"`
}

func (m *MemberStatusResponse) Reset()                    { *m = MemberStatusResponse{} }
func (m *MemberStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberStatusResponse) ProtoMessage()               {}
func (*MemberStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MemberStatusResponse) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberStatusResponse) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *MemberStatusResponse) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *MemberStatusResponse) GetInvited() *google_protobuf.Timestamp {
	if m != nil {
		return m.Invited
	}
	return nil
}

func (m *MemberStatusResponse) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *MemberStatusResponse) GetJoined() *google_protobuf.Timestamp {
	if m != nil {
		return m.Joined
	}
	return nil
}

func (m *MemberStatusResponse) GetDetached() *google_protobuf.Timestamp {
	if m != nil {
		return m.Detached
	}
	return nil
}

type GetMembersRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *GetMembersRequest) Reset()                    { *m = GetMembersRequest{} }
func (m *GetMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMembersRequest) ProtoMessage()               {}
func (*GetMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetMembersRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetProjectsRequest struct {
	MemberId string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
}

func (m *GetProjectsRequest) Reset()                    { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()               {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetProjectsRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type MembersResponse struct {
	Members map[string]*MemberStatusResponse `protobuf:"bytes,1,rep,name=members" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MembersResponse) Reset()                    { *m = MembersResponse{} }
func (m *MembersResponse) String() string            { return proto.CompactTextString(m) }
func (*MembersResponse) ProtoMessage()               {}
func (*MembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MembersResponse) GetMembers() map[string]*MemberStatusResponse {
	if m != nil {
		return m.Members
	}
	return nil
}

type ProjectsResponse struct {
	Projects map[string]*ProjectResponse `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ProjectsResponse) Reset()                    { *m = ProjectsResponse{} }
func (m *ProjectsResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectsResponse) ProtoMessage()               {}
func (*ProjectsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ProjectsResponse) GetProjects() map[string]*ProjectResponse {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "projects.CreateRequest")
	proto.RegisterType((*RetrieveRequest)(nil), "projects.RetrieveRequest")
	proto.RegisterType((*ProjectResponse)(nil), "projects.ProjectResponse")
	proto.RegisterType((*AddMemberRequest)(nil), "projects.AddMemberRequest")
	proto.RegisterType((*RemoveMemberRequest)(nil), "projects.RemoveMemberRequest")
	proto.RegisterType((*InviteRequest)(nil), "projects.InviteRequest")
	proto.RegisterType((*InviteStatusResponse)(nil), "projects.InviteStatusResponse")
	proto.RegisterType((*ActionInviteRequest)(nil), "projects.ActionInviteRequest")
	proto.RegisterType((*MemberStatusResponse)(nil), "projects.MemberStatusResponse")
	proto.RegisterType((*GetMembersRequest)(nil), "projects.GetMembersRequest")
	proto.RegisterType((*GetProjectsRequest)(nil), "projects.GetProjectsRequest")
	proto.RegisterType((*MembersResponse)(nil), "projects.MembersResponse")
	proto.RegisterType((*ProjectsResponse)(nil), "projects.ProjectsResponse")
	proto.RegisterEnum("projects.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("projects.Region", Region_name, Region_value)
	proto.RegisterEnum("projects.MemberType", MemberType_name, MemberType_value)
	proto.RegisterEnum("projects.InviteStatus", InviteStatus_name, InviteStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Projects service

type ProjectsClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error)
	Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error)
	ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error) {
	out := new(ProjectsResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/GetProjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/AddMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/RemoveMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error) {
	out := new(MembersResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/GetMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error) {
	out := new(InviteStatusResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/Invite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/projects.Projects/ActionInvite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Projects service

type ProjectsServer interface {
	Create(context.Context, *CreateRequest) (*ProjectResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*ProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*ProjectsResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*MemberStatusResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*MemberStatusResponse, error)
	GetMembers(context.Context, *GetMembersRequest) (*MembersResponse, error)
	Invite(context.Context, *InviteRequest) (*InviteStatusResponse, error)
	ActionInvite(context.Context, *ActionInviteRequest) (*MemberStatusResponse, error)
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Invite(ctx, req.(*InviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_ActionInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ActionInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projects.Projects/ActionInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ActionInvite(ctx, req.(*ActionInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projects.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Projects_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Projects_Retrieve_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _Projects_GetProjects_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _Projects_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _Projects_RemoveMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _Projects_GetMembers_Handler,
		},
		{
			MethodName: "Invite",
			Handler:    _Projects_Invite_Handler,
		},
		{
			MethodName: "ActionInvite",
			Handler:    _Projects_ActionInvite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projects.proto",
}

func init() { proto.RegisterFile("projects.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x56, 0xdb, 0x8e, 0x1a, 0x47,
	0x13, 0xde, 0x86, 0x61, 0x80, 0xe2, 0xb0, 0xf3, 0xb7, 0x57, 0x7f, 0x30, 0x8e, 0x93, 0xcd, 0xe4,
	0x20, 0xb4, 0x52, 0x40, 0x99, 0xac, 0xa2, 0x28, 0xf2, 0x85, 0x59, 0x98, 0x20, 0x22, 0x73, 0x48,
	0x03, 0xb6, 0xe5, 0x9b, 0x15, 0x30, 0x6d, 0x3c, 0xce, 0x0e, 0x43, 0x66, 0x1a, 0x64, 0x5e, 0x27,
	0x57, 0xb9, 0x88, 0x94, 0xdc, 0xe7, 0x32, 0x6f, 0x90, 0x27, 0xc8, 0x13, 0xe4, 0x19, 0xa2, 0xe9,
	0x9e, 0x23, 0xcb, 0xee, 0xa2, 0xc8, 0x4a, 0x72, 0x37, 0x5d, 0xf5, 0x75, 0xcf, 0x57, 0x55, 0x5f,
	0x77, 0x15, 0x94, 0x57, 0x8e, 0xfd, 0x9a, 0xce, 0x99, 0x5b, 0x5f, 0x39, 0x36, 0xb3, 0x71, 0x2e,
	0x58, 0x57, 0xdf, 0x5f, 0xd8, 0xf6, 0xe2, 0x8a, 0x36, 0xb8, 0x7d, 0xb6, 0x7e, 0xd9, 0x60, 0xa6,
	0x45, 0x5d, 0x36, 0xb5, 0x56, 0x02, 0xaa, 0xfe, 0x88, 0xa0, 0xd4, 0x72, 0xe8, 0x94, 0x51, 0x42,
	0xbf, 0x5f, 0x53, 0x97, 0xe1, 0x32, 0xa4, 0x4c, 0xa3, 0x82, 0x4e, 0x51, 0x2d, 0x4f, 0x52, 0xa6,
	0x81, 0x31, 0x48, 0xcb, 0xa9, 0x45, 0x2b, 0x29, 0x6e, 0xe1, 0xdf, 0xf8, 0x63, 0x28, 0x1b, 0xa6,
	0xcb, 0x1c, 0x73, 0xb6, 0x66, 0xb6, 0x73, 0x69, 0x1a, 0x95, 0x34, 0xf7, 0x96, 0x62, 0xd6, 0xae,
	0x81, 0x55, 0x90, 0x2c, 0xdb, 0xa0, 0x15, 0xe9, 0x14, 0xd5, 0xca, 0x5a, 0xb9, 0x1e, 0xd2, 0xec,
	0xd9, 0x06, 0x25, 0xdc, 0x87, 0x6b, 0x20, 0x3b, 0x74, 0x61, 0xda, 0xcb, 0x4a, 0x86, 0xa3, 0x94,
	0x08, 0x45, 0xb8, 0x9d, 0xf8, 0x7e, 0xf5, 0x03, 0x38, 0x26, 0x94, 0x39, 0x26, 0xdd, 0xdc, 0xc4,
	0x55, 0xfd, 0x03, 0xc1, 0xf1, 0x50, 0x6c, 0x27, 0xd4, 0x5d, 0xd9, 0x4b, 0x97, 0xfe, 0x67, 0xe3,
	0xc1, 0xe7, 0x90, 0x9d, 0xf3, 0xcc, 0x1b, 0x15, 0xf9, 0x14, 0xd5, 0x0a, 0x5a, 0xb5, 0x2e, 0xaa,
	0x55, 0x0f, 0xaa, 0x55, 0x1f, 0x07, 0xd5, 0x22, 0x01, 0x54, 0xfd, 0x09, 0x81, 0xd2, 0x34, 0x8c,
	0x1e, 0xb5, 0x66, 0xd4, 0x09, 0xf2, 0xf0, 0x00, 0xf2, 0x16, 0x37, 0x5c, 0x86, 0xa1, 0xe6, 0x84,
	0xa1, 0x6b, 0xe0, 0x87, 0x00, 0x3e, 0x05, 0xcf, 0x2b, 0xc2, 0xce, 0xfb, 0x96, 0xae, 0x81, 0x6b,
	0x20, 0xb1, 0xed, 0x8a, 0xf2, 0x88, 0xcb, 0xda, 0x49, 0x2c, 0x28, 0x7e, 0xc0, 0x78, 0xbb, 0xa2,
	0x84, 0x23, 0xb0, 0x06, 0x32, 0x7d, 0xb3, 0x32, 0x9d, 0x2d, 0x4f, 0xc0, 0xed, 0x7c, 0x7d, 0xa4,
	0xfa, 0x2d, 0xdc, 0x23, 0xd4, 0xb2, 0x37, 0xf4, 0xad, 0x11, 0x56, 0x7f, 0x40, 0x50, 0xea, 0x2e,
	0x37, 0x66, 0x24, 0xd9, 0x13, 0xc8, 0x50, 0x6b, 0x6a, 0x5e, 0xf9, 0x27, 0x89, 0xc5, 0xbf, 0x1b,
	0xf7, 0x9f, 0x08, 0x4e, 0x04, 0xc9, 0x11, 0x9b, 0xb2, 0xb5, 0x1b, 0xca, 0x71, 0x3f, 0xd7, 0x3a,
	0xc8, 0x2e, 0xc7, 0x71, 0x9e, 0x65, 0xed, 0xff, 0x11, 0x9d, 0xc4, 0x29, 0x3e, 0x0a, 0xab, 0x50,
	0xdc, 0x50, 0xc7, 0x7c, 0x69, 0xce, 0xa7, 0xcc, 0xd3, 0x9a, 0x90, 0x6b, 0xc2, 0x16, 0xd7, 0x97,
	0x74, 0xb0, 0xbe, 0xf0, 0x17, 0x90, 0x9b, 0xce, 0xbd, 0xfd, 0xd4, 0xe0, 0x0a, 0xbe, 0x7d, 0x5b,
	0x88, 0x55, 0x7f, 0x45, 0x70, 0xaf, 0xc9, 0x17, 0x6f, 0xa1, 0x36, 0x09, 0x79, 0xa4, 0x77, 0xe4,
	0x11, 0xe5, 0x4a, 0xfa, 0x5b, 0xb9, 0xca, 0x5c, 0xcf, 0x95, 0xfa, 0x7b, 0x0a, 0x4e, 0x44, 0xdd,
	0x77, 0xca, 0xf5, 0xcf, 0xdc, 0xac, 0x73, 0xc8, 0x9a, 0x9c, 0xfa, 0x41, 0xa5, 0xf2, 0xa1, 0x31,
	0x5d, 0x66, 0x0e, 0xd5, 0xa5, 0xb7, 0xe7, 0xb5, 0x6d, 0x2e, 0x0f, 0x7a, 0x73, 0x7c, 0xa4, 0x27,
	0x09, 0x83, 0xb2, 0xe9, 0xfc, 0x15, 0x35, 0x2a, 0xd9, 0xbb, 0x25, 0x11, 0x60, 0x55, 0x0d, 0xfe,
	0xd7, 0xa1, 0x4c, 0x04, 0xeb, 0x06, 0x7a, 0x48, 0xe6, 0x0c, 0xed, 0x5e, 0xee, 0xcf, 0x00, 0x77,
	0x28, 0xf3, 0xdf, 0x70, 0xf7, 0x90, 0xe7, 0x42, 0xfd, 0x19, 0xc1, 0x71, 0xf8, 0x13, 0xbf, 0x6c,
	0x8f, 0x21, 0x2b, 0xfc, 0x6e, 0x05, 0x9d, 0xa6, 0x6b, 0x05, 0xed, 0x93, 0xdd, 0xec, 0x87, 0xd8,
	0x60, 0xad, 0x2f, 0x99, 0xb3, 0x25, 0xc1, 0xb6, 0xea, 0x0b, 0x28, 0xc6, 0x1d, 0x58, 0x81, 0xf4,
	0x77, 0x74, 0xeb, 0xff, 0xdc, 0xfb, 0xc4, 0xe7, 0x90, 0xd9, 0x4c, 0xaf, 0xd6, 0xa2, 0x93, 0x14,
	0xb4, 0xf7, 0x76, 0xff, 0x90, 0x54, 0x12, 0x11, 0xe0, 0xaf, 0x52, 0x5f, 0x22, 0xf5, 0x17, 0x04,
	0x4a, 0x14, 0xa2, 0x4f, 0xb9, 0x0d, 0x61, 0xdb, 0xf6, 0x39, 0xd7, 0xa2, 0x13, 0x77, 0xd1, 0xa1,
	0x41, 0xb0, 0x8e, 0x1a, 0xfe, 0x53, 0x28, 0x25, 0x5c, 0x7b, 0x78, 0x37, 0x92, 0xbc, 0xef, 0x5f,
	0xfb, 0xcb, 0x1e, 0xca, 0x67, 0x1f, 0x82, 0xe4, 0x35, 0x39, 0x5c, 0x80, 0xec, 0xa8, 0xd9, 0x6f,
	0x5f, 0x0c, 0x9e, 0x2b, 0x47, 0xb8, 0x0c, 0x30, 0x24, 0x83, 0xf6, 0xa4, 0x35, 0xee, 0x0e, 0xfa,
	0x0a, 0x3a, 0xd3, 0x40, 0x16, 0x3d, 0x0e, 0x03, 0xc8, 0x9d, 0x27, 0x83, 0x8b, 0xe6, 0x13, 0xe5,
	0x08, 0xcb, 0x90, 0x9a, 0x8c, 0x14, 0xe4, 0xd9, 0xf4, 0x09, 0x19, 0x0c, 0x75, 0x25, 0x85, 0x73,
	0x20, 0x35, 0x47, 0xdd, 0xa6, 0x92, 0x3e, 0x7b, 0x04, 0x10, 0x5d, 0x07, 0x9c, 0x87, 0xcc, 0xe0,
	0x59, 0x5f, 0x27, 0xca, 0x91, 0x07, 0xef, 0xe9, 0xbd, 0x0b, 0x9d, 0x88, 0xad, 0x4f, 0xbb, 0xfa,
	0x33, 0x9d, 0x28, 0x29, 0xce, 0x60, 0x32, 0x1c, 0x0e, 0xc8, 0x58, 0x49, 0x9f, 0x8d, 0xa0, 0x18,
	0xbf, 0xf3, 0x9e, 0x73, 0xa8, 0xf7, 0xdb, 0xdd, 0x7e, 0x47, 0x39, 0xc2, 0x45, 0xc8, 0x35, 0x5b,
	0x2d, 0x7d, 0x38, 0xd6, 0xdb, 0x0a, 0xf2, 0x56, 0x44, 0xff, 0x46, 0x6f, 0x79, 0x2b, 0x7e, 0x8a,
	0xfe, 0x7c, 0xd8, 0x25, 0x7a, 0x5b, 0x49, 0xe3, 0x12, 0xe4, 0xfb, 0x83, 0xf1, 0xe5, 0xd7, 0x83,
	0x49, 0xbf, 0xad, 0x48, 0xda, 0x6f, 0x12, 0xe4, 0x82, 0x24, 0xe2, 0x47, 0x20, 0x8b, 0xf9, 0x08,
	0xbf, 0x13, 0x25, 0x2a, 0x31, 0x31, 0x55, 0x6f, 0xce, 0x20, 0x7e, 0x0c, 0xb9, 0x60, 0x66, 0xc1,
	0xf7, 0xe3, 0x93, 0x40, 0x62, 0x8e, 0xb9, 0xed, 0x84, 0x0e, 0x14, 0x62, 0x17, 0x02, 0xbf, 0x1b,
	0x21, 0xaf, 0xdf, 0x93, 0x6a, 0xf5, 0x66, 0xc5, 0xe0, 0x0e, 0xe4, 0xc3, 0xb9, 0x01, 0xc7, 0x80,
	0xbb, 0xc3, 0x44, 0xf5, 0x0e, 0x21, 0xe3, 0x1e, 0x14, 0xe3, 0x2d, 0x1d, 0x3f, 0x8c, 0xc7, 0x75,
	0xad, 0xd5, 0xdf, 0x79, 0x5c, 0x1b, 0x20, 0x7a, 0x25, 0xf0, 0x83, 0x44, 0x7c, 0xc9, 0xb7, 0x23,
	0x9e, 0xa6, 0xdd, 0x0b, 0xdf, 0x04, 0x59, 0x08, 0x21, 0x5e, 0xa6, 0x44, 0x27, 0x8a, 0x13, 0xd9,
	0xdb, 0x99, 0x7b, 0x50, 0x8c, 0x37, 0xb0, 0x78, 0x5c, 0x7b, 0x1a, 0xdb, 0x5d, 0x71, 0x5d, 0x7c,
	0xf4, 0x42, 0x5d, 0x98, 0xec, 0xd5, 0x7a, 0x56, 0x9f, 0xdb, 0x56, 0x63, 0xbe, 0x9e, 0xd1, 0x37,
	0x62, 0x0c, 0xff, 0x74, 0x61, 0x37, 0x82, 0xad, 0x33, 0x99, 0x9b, 0x3e, 0xff, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0x02, 0xa0, 0xf1, 0xe7, 0xc3, 0x0b, 0x00, 0x00,
}
