// Code generated by protoc-gen-go.
// source: sockets.proto
// DO NOT EDIT!

/*
Package sockets is a generated protocol buffer package.

It is generated from these files:
	sockets.proto

It has these top-level messages:
	SocketMessage
	SubscribeMessage
	PublishResponse
*/
package sockets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocketMessage struct {
	AppId   string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	Action  string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Payload string `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (m *SocketMessage) Reset()                    { *m = SocketMessage{} }
func (m *SocketMessage) String() string            { return proto.CompactTextString(m) }
func (*SocketMessage) ProtoMessage()               {}
func (*SocketMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SocketMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SocketMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SocketMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *SocketMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type SubscribeMessage struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AppId     string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Channel   string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *SubscribeMessage) Reset()                    { *m = SubscribeMessage{} }
func (m *SubscribeMessage) String() string            { return proto.CompactTextString(m) }
func (*SubscribeMessage) ProtoMessage()               {}
func (*SubscribeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeMessage) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SubscribeMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SubscribeMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type PublishResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PublishResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*SocketMessage)(nil), "sockets.SocketMessage")
	proto.RegisterType((*SubscribeMessage)(nil), "sockets.SubscribeMessage")
	proto.RegisterType((*PublishResponse)(nil), "sockets.PublishResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sockets service

type SocketsClient interface {
	Publish(ctx context.Context, in *SocketMessage, opts ...grpc.CallOption) (*PublishResponse, error)
	Subscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error)
	UnSubscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error)
}

type socketsClient struct {
	cc *grpc.ClientConn
}

func NewSocketsClient(cc *grpc.ClientConn) SocketsClient {
	return &socketsClient{cc}
}

func (c *socketsClient) Publish(ctx context.Context, in *SocketMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/sockets.Sockets/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketsClient) Subscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/sockets.Sockets/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketsClient) UnSubscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/sockets.Sockets/UnSubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sockets service

type SocketsServer interface {
	Publish(context.Context, *SocketMessage) (*PublishResponse, error)
	Subscribe(context.Context, *SubscribeMessage) (*PublishResponse, error)
	UnSubscribe(context.Context, *SubscribeMessage) (*PublishResponse, error)
}

func RegisterSocketsServer(s *grpc.Server, srv SocketsServer) {
	s.RegisterService(&_Sockets_serviceDesc, srv)
}

func _Sockets_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketsServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sockets.Sockets/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketsServer).Publish(ctx, req.(*SocketMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sockets_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketsServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sockets.Sockets/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketsServer).Subscribe(ctx, req.(*SubscribeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sockets_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketsServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sockets.Sockets/UnSubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketsServer).UnSubscribe(ctx, req.(*SubscribeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sockets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sockets.Sockets",
	HandlerType: (*SocketsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Sockets_Publish_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Sockets_Subscribe_Handler,
		},
		{
			MethodName: "UnSubscribe",
			Handler:    _Sockets_UnSubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sockets.proto",
}

func init() { proto.RegisterFile("sockets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xd9, 0xf6, 0x5f, 0xfb, 0xef, 0x2b, 0x43, 0x09, 0x3a, 0xa2, 0x20, 0x68, 0xbd, 0x78,
	0xb1, 0x05, 0x3d, 0x7a, 0xd1, 0xdd, 0x76, 0x10, 0xa4, 0xc3, 0x8b, 0x17, 0x49, 0xd2, 0xd0, 0x06,
	0x6b, 0x12, 0xf2, 0xb6, 0xa0, 0xdf, 0xd1, 0x0f, 0x25, 0xcb, 0xd2, 0xcd, 0x0d, 0xf4, 0xe2, 0xad,
	0xbf, 0xa7, 0x79, 0x9e, 0xf7, 0xcd, 0x43, 0x60, 0x82, 0x46, 0xbc, 0xca, 0x16, 0x33, 0xeb, 0x4c,
	0x6b, 0x48, 0x1c, 0x30, 0x75, 0x30, 0x59, 0xf8, 0xcf, 0x07, 0x89, 0xc8, 0x2a, 0x49, 0x8e, 0x20,
	0x62, 0xd6, 0xbe, 0xa8, 0x92, 0x0e, 0xce, 0x06, 0x97, 0x49, 0x31, 0x66, 0xd6, 0xce, 0x4b, 0x42,
	0x21, 0x16, 0x35, 0xd3, 0x5a, 0x36, 0x74, 0xe8, 0xf5, 0x1e, 0xc9, 0x14, 0x22, 0x26, 0x5a, 0x65,
	0x34, 0x1d, 0xf9, 0x1f, 0x81, 0x96, 0x0e, 0xcb, 0x3e, 0x1a, 0xc3, 0x4a, 0xfa, 0x6f, 0xe5, 0x08,
	0x98, 0x72, 0x38, 0x58, 0x74, 0x1c, 0x85, 0x53, 0x5c, 0xf6, 0x63, 0x4f, 0x01, 0x50, 0x22, 0x2a,
	0xa3, 0x37, 0xa3, 0x93, 0xa0, 0xcc, 0xcb, 0x6f, 0x5b, 0x0d, 0x7f, 0xd8, 0x6a, 0xb4, 0xb5, 0x55,
	0x7a, 0x0f, 0xfb, 0x8f, 0x1d, 0x6f, 0x14, 0xd6, 0x85, 0x44, 0x6b, 0x34, 0xca, 0xe5, 0x61, 0xec,
	0x84, 0x90, 0x88, 0x3e, 0xff, 0x7f, 0xd1, 0x23, 0x39, 0x84, 0xb1, 0x74, 0xce, 0xb8, 0x3e, 0xdc,
	0xc3, 0xf5, 0xe7, 0x00, 0xe2, 0x55, 0x37, 0x48, 0x6e, 0x21, 0x0e, 0x71, 0x64, 0x9a, 0xf5, 0x55,
	0x6e, 0x15, 0x77, 0x42, 0xd7, 0xfa, 0xee, 0xe0, 0x3b, 0x48, 0xd6, 0xf7, 0x25, 0xc7, 0x1b, 0xfb,
	0x4e, 0x07, 0xbf, 0x24, 0xcc, 0x60, 0xef, 0x49, 0xff, 0x2d, 0x63, 0x76, 0xf1, 0x7c, 0x5e, 0xa9,
	0xb6, 0xee, 0x78, 0x26, 0xcc, 0x5b, 0x2e, 0x3a, 0x2e, 0xdf, 0x73, 0xff, 0x18, 0xae, 0x2a, 0x93,
	0x07, 0x13, 0x8f, 0xbc, 0x72, 0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x53, 0xa0, 0x4b, 0x2f,
	0x02, 0x00, 0x00,
}
