// Code generated by protoc-gen-go.
// source: platform.proto
// DO NOT EDIT!

/*
Package platform is a generated protocol buffer package.

It is generated from these files:
	platform.proto

It has these top-level messages:
	HTTPRequest
	HTTPResponse
	SocketRequest
*/
package platform

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocketAction int32

const (
	SocketAction_SUBSCRIBE   SocketAction = 0
	SocketAction_UNSUBSCRIBE SocketAction = 1
)

var SocketAction_name = map[int32]string{
	0: "SUBSCRIBE",
	1: "UNSUBSCRIBE",
}
var SocketAction_value = map[string]int32{
	"SUBSCRIBE":   0,
	"UNSUBSCRIBE": 1,
}

func (x SocketAction) String() string {
	return proto.EnumName(SocketAction_name, int32(x))
}
func (SocketAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HTTPRequest_RequestType int32

const (
	HTTPRequest_REQUEST         HTTPRequest_RequestType = 0
	HTTPRequest_PAGE_DEFINITION HTTPRequest_RequestType = 1
)

var HTTPRequest_RequestType_name = map[int32]string{
	0: "REQUEST",
	1: "PAGE_DEFINITION",
}
var HTTPRequest_RequestType_value = map[string]int32{
	"REQUEST":         0,
	"PAGE_DEFINITION": 1,
}

func (x HTTPRequest_RequestType) String() string {
	return proto.EnumName(HTTPRequest_RequestType_name, int32(x))
}
func (HTTPRequest_RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type HTTPRequest struct {
	Path        string                                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Method      string                                `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	PostParams  map[string]*HTTPRequest_HTTPParameter `protobuf:"bytes,3,rep,name=post_params,json=postParams" json:"post_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryString string                                `protobuf:"bytes,4,opt,name=query_string,json=queryString" json:"query_string,omitempty"`
	Body        string                                `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	Language    string                                `protobuf:"bytes,6,opt,name=language" json:"language,omitempty"`
	ContentType string                                `protobuf:"bytes,7,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	RequestType HTTPRequest_RequestType               `protobuf:"varint,8,opt,name=request_type,json=requestType,enum=platform.HTTPRequest_RequestType" json:"request_type,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HTTPRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetPostParams() map[string]*HTTPRequest_HTTPParameter {
	if m != nil {
		return m.PostParams
	}
	return nil
}

func (m *HTTPRequest) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *HTTPRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *HTTPRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *HTTPRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *HTTPRequest) GetRequestType() HTTPRequest_RequestType {
	if m != nil {
		return m.RequestType
	}
	return HTTPRequest_REQUEST
}

type HTTPRequest_HTTPParameter struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HTTPRequest_HTTPParameter) Reset()                    { *m = HTTPRequest_HTTPParameter{} }
func (m *HTTPRequest_HTTPParameter) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest_HTTPParameter) ProtoMessage()               {}
func (*HTTPRequest_HTTPParameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *HTTPRequest_HTTPParameter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type HTTPResponse struct {
	StatusCode  int32                                        `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Body        string                                       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	ContentType string                                       `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Language    string                                       `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Headers     map[string]*HTTPResponse_HTTPHeaderParameter `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HTTPResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *HTTPResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *HTTPResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *HTTPResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *HTTPResponse) GetHeaders() map[string]*HTTPResponse_HTTPHeaderParameter {
	if m != nil {
		return m.Headers
	}
	return nil
}

type HTTPResponse_HTTPHeaderParameter struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HTTPResponse_HTTPHeaderParameter) Reset()         { *m = HTTPResponse_HTTPHeaderParameter{} }
func (m *HTTPResponse_HTTPHeaderParameter) String() string { return proto.CompactTextString(m) }
func (*HTTPResponse_HTTPHeaderParameter) ProtoMessage()    {}
func (*HTTPResponse_HTTPHeaderParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *HTTPResponse_HTTPHeaderParameter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type SocketRequest struct {
	SocketId string       `protobuf:"bytes,1,opt,name=socket_id,json=socketId" json:"socket_id,omitempty"`
	Action   SocketAction `protobuf:"varint,2,opt,name=action,enum=platform.SocketAction" json:"action,omitempty"`
	Payload  string       `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *SocketRequest) Reset()                    { *m = SocketRequest{} }
func (m *SocketRequest) String() string            { return proto.CompactTextString(m) }
func (*SocketRequest) ProtoMessage()               {}
func (*SocketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SocketRequest) GetSocketId() string {
	if m != nil {
		return m.SocketId
	}
	return ""
}

func (m *SocketRequest) GetAction() SocketAction {
	if m != nil {
		return m.Action
	}
	return SocketAction_SUBSCRIBE
}

func (m *SocketRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*HTTPRequest)(nil), "platform.HTTPRequest")
	proto.RegisterType((*HTTPRequest_HTTPParameter)(nil), "platform.HTTPRequest.HTTPParameter")
	proto.RegisterType((*HTTPResponse)(nil), "platform.HTTPResponse")
	proto.RegisterType((*HTTPResponse_HTTPHeaderParameter)(nil), "platform.HTTPResponse.HTTPHeaderParameter")
	proto.RegisterType((*SocketRequest)(nil), "platform.SocketRequest")
	proto.RegisterEnum("platform.SocketAction", SocketAction_name, SocketAction_value)
	proto.RegisterEnum("platform.HTTPRequest_RequestType", HTTPRequest_RequestType_name, HTTPRequest_RequestType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CubexPlatform service

type CubexPlatformClient interface {
	HandleHTTPRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
	HandleSocketAction(ctx context.Context, in *SocketRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type cubexPlatformClient struct {
	cc *grpc.ClientConn
}

func NewCubexPlatformClient(cc *grpc.ClientConn) CubexPlatformClient {
	return &cubexPlatformClient{cc}
}

func (c *cubexPlatformClient) HandleHTTPRequest(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := grpc.Invoke(ctx, "/platform.cubexPlatform/HandleHTTPRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubexPlatformClient) HandleSocketAction(ctx context.Context, in *SocketRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := grpc.Invoke(ctx, "/platform.cubexPlatform/HandleSocketAction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CubexPlatform service

type CubexPlatformServer interface {
	HandleHTTPRequest(context.Context, *HTTPRequest) (*HTTPResponse, error)
	HandleSocketAction(context.Context, *SocketRequest) (*HTTPResponse, error)
}

func RegisterCubexPlatformServer(s *grpc.Server, srv CubexPlatformServer) {
	s.RegisterService(&_CubexPlatform_serviceDesc, srv)
}

func _CubexPlatform_HandleHTTPRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubexPlatformServer).HandleHTTPRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.cubexPlatform/HandleHTTPRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubexPlatformServer).HandleHTTPRequest(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubexPlatform_HandleSocketAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubexPlatformServer).HandleSocketAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.cubexPlatform/HandleSocketAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubexPlatformServer).HandleSocketAction(ctx, req.(*SocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CubexPlatform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "platform.cubexPlatform",
	HandlerType: (*CubexPlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHTTPRequest",
			Handler:    _CubexPlatform_HandleHTTPRequest_Handler,
		},
		{
			MethodName: "HandleSocketAction",
			Handler:    _CubexPlatform_HandleSocketAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}

func init() { proto.RegisterFile("platform.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xcb, 0x6e, 0xda, 0x4c,
	0x18, 0x8d, 0x71, 0xb8, 0xe4, 0x33, 0xb7, 0x7f, 0xa2, 0x9f, 0x5a, 0x74, 0x51, 0x42, 0x5b, 0x15,
	0x45, 0x8a, 0x91, 0xe8, 0xa6, 0xad, 0x54, 0xa9, 0x21, 0x71, 0x0a, 0x1b, 0x4a, 0x0d, 0x6c, 0xba,
	0xb1, 0x06, 0x7b, 0x02, 0x28, 0xe0, 0x71, 0x3c, 0xe3, 0xa8, 0x7e, 0x95, 0x3e, 0x59, 0xdf, 0xa5,
	0x9b, 0xca, 0x33, 0x06, 0xcc, 0xa5, 0xca, 0xca, 0xf3, 0x9d, 0xf9, 0x2e, 0x67, 0xce, 0x19, 0x0f,
	0x94, 0xfd, 0x25, 0xe6, 0xf7, 0x34, 0x58, 0x19, 0x7e, 0x40, 0x39, 0x45, 0x85, 0x75, 0xdc, 0xfc,
	0xa3, 0x82, 0xd6, 0x1b, 0x8f, 0x87, 0x16, 0x79, 0x0c, 0x09, 0xe3, 0x08, 0xc1, 0xa9, 0x8f, 0xf9,
	0x5c, 0x57, 0x1a, 0x4a, 0xeb, 0xcc, 0x12, 0x6b, 0x54, 0x83, 0xdc, 0x8a, 0xf0, 0x39, 0x75, 0xf5,
	0x8c, 0x40, 0x93, 0x08, 0xdd, 0x81, 0xe6, 0x53, 0xc6, 0x6d, 0x1f, 0x07, 0x78, 0xc5, 0x74, 0xb5,
	0xa1, 0xb6, 0xb4, 0xce, 0x5b, 0x63, 0x33, 0x2b, 0xd5, 0xd7, 0x18, 0x52, 0xc6, 0x87, 0x22, 0xcf,
	0xf4, 0x78, 0x10, 0x59, 0xe0, 0x6f, 0x00, 0x74, 0x01, 0xc5, 0xc7, 0x90, 0x04, 0x91, 0xcd, 0x78,
	0xb0, 0xf0, 0x66, 0xfa, 0xa9, 0x98, 0xa2, 0x09, 0x6c, 0x24, 0xa0, 0x98, 0xd6, 0x94, 0xba, 0x91,
	0x9e, 0x95, 0xb4, 0xe2, 0x35, 0xaa, 0x43, 0x61, 0x89, 0xbd, 0x59, 0x88, 0x67, 0x44, 0xcf, 0x09,
	0x7c, 0x13, 0xc7, 0x2d, 0x1d, 0xea, 0x71, 0xe2, 0x71, 0x9b, 0x47, 0x3e, 0xd1, 0xf3, 0xb2, 0x65,
	0x82, 0x8d, 0x23, 0x9f, 0xa0, 0x5b, 0x28, 0x06, 0x92, 0x9c, 0x4c, 0x29, 0x34, 0x94, 0x56, 0xb9,
	0x73, 0x71, 0x9c, 0x7e, 0xf2, 0x8d, 0x0b, 0x2d, 0x2d, 0xd8, 0x06, 0xf5, 0x77, 0x50, 0x8a, 0xf3,
	0xc4, 0x49, 0x08, 0x27, 0x41, 0x2c, 0xd6, 0x13, 0x5e, 0x86, 0x84, 0xe9, 0x4a, 0x43, 0x8d, 0xc5,
	0x92, 0x51, 0x7d, 0x0a, 0x95, 0x3d, 0x0d, 0x50, 0x15, 0xd4, 0x07, 0x12, 0x25, 0x52, 0xc7, 0x4b,
	0xf4, 0x11, 0xb2, 0x22, 0x5d, 0x08, 0xad, 0x75, 0x5e, 0x1f, 0x27, 0xb3, 0x33, 0xd0, 0x92, 0x15,
	0x9f, 0x32, 0x1f, 0x94, 0x66, 0x1b, 0xb4, 0x14, 0x51, 0xa4, 0x41, 0xde, 0x32, 0xbf, 0x4f, 0xcc,
	0xd1, 0xb8, 0x7a, 0x82, 0xce, 0xa1, 0x32, 0xbc, 0xfe, 0x6a, 0xda, 0xb7, 0xe6, 0x5d, 0x7f, 0xd0,
	0x1f, 0xf7, 0xbf, 0x0d, 0xaa, 0x4a, 0xf3, 0x77, 0x06, 0x8a, 0xb2, 0x33, 0xf3, 0xa9, 0xc7, 0x08,
	0x7a, 0x05, 0x1a, 0xe3, 0x98, 0x87, 0xcc, 0x76, 0xa8, 0x4b, 0x04, 0xb5, 0xac, 0x05, 0x12, 0xba,
	0xa1, 0x2e, 0xd9, 0x18, 0x91, 0x49, 0x19, 0xb1, 0x2f, 0xb6, 0x7a, 0x28, 0x76, 0xda, 0xab, 0xd3,
	0x3d, 0xaf, 0x3e, 0x43, 0x7e, 0x4e, 0xb0, 0x4b, 0x02, 0xa6, 0x67, 0xc5, 0x15, 0x3a, 0x38, 0xb6,
	0x24, 0x67, 0xf4, 0x64, 0x96, 0xbc, 0x40, 0xeb, 0x9a, 0xfa, 0x15, 0x9c, 0xc7, 0x59, 0x72, 0xf3,
	0x79, 0x1f, 0xee, 0xa1, 0x98, 0xee, 0x73, 0xc4, 0x84, 0x2f, 0xbb, 0x26, 0x5c, 0xfe, 0x8b, 0xcd,
	0xe1, 0xd0, 0xb4, 0x17, 0x4f, 0x50, 0x1a, 0x51, 0xe7, 0x81, 0xf0, 0xf5, 0x9f, 0xf5, 0x12, 0xce,
	0x98, 0x00, 0xec, 0x85, 0x9b, 0x8c, 0x2b, 0x48, 0xa0, 0xef, 0x22, 0x03, 0x72, 0xd8, 0xe1, 0x0b,
	0xea, 0x89, 0xa1, 0xe5, 0x4e, 0x6d, 0x3b, 0x54, 0x76, 0xb9, 0x16, 0xbb, 0x56, 0x92, 0x85, 0x74,
	0xc8, 0xfb, 0x38, 0x5a, 0x52, 0xec, 0x26, 0x6a, 0xaf, 0xc3, 0x4b, 0x03, 0x8a, 0xe9, 0x0a, 0x54,
	0x82, 0xb3, 0xd1, 0xa4, 0x3b, 0xba, 0xb1, 0xfa, 0x5d, 0xb3, 0x7a, 0x82, 0x2a, 0xa0, 0x4d, 0x06,
	0x5b, 0x40, 0xe9, 0xfc, 0x52, 0xa0, 0xe4, 0x84, 0x53, 0xf2, 0x73, 0x98, 0x0c, 0x44, 0x5d, 0xf8,
	0xaf, 0x87, 0x3d, 0x77, 0x49, 0xd2, 0xef, 0xc2, 0xff, 0x47, 0xaf, 0x62, 0xbd, 0x76, 0x5c, 0x1c,
	0x64, 0x02, 0x92, 0x3d, 0x76, 0xb8, 0xbc, 0xd8, 0x3f, 0xd5, 0x33, 0x6d, 0xba, 0x6f, 0x7e, 0x34,
	0x67, 0x0b, 0x3e, 0x0f, 0xa7, 0x86, 0x43, 0x57, 0x6d, 0x41, 0xb3, 0x2d, 0x5e, 0xb0, 0xab, 0x19,
	0x6d, 0xaf, 0x4b, 0xa6, 0x39, 0x01, 0xbd, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x44, 0xf2,
	0x1f, 0xe6, 0x04, 0x00, 0x00,
}
